### ISSUE TITLE
The plugin doesn't support watch mode.

### ISSUE THREAD

**Issue by limbowang** [tsne/rollup-plugin-tsc#1]
Is there any way to support watch mode?

**Comment by tsne** [comment]
Hi @limbowang,

I made some small changes which should also address this issue. I tried the watch mode with rollup@0.50.0 and it seems to work. Can you please update the plugin and try the watch mode again?

**Comment by limbowang** [comment]
@tsne Not works for me. File changes trigger new buildings but not actually build with new file content. But I find that updating the version in filestore->read function when file content changes might solve it.
```javascript
read(filename) {
  
  filename = normalizePath(filename);
  let f = files[filename];
  if(!f) {
    f = newFile(filename);
  }
  var content = fs.readFileSync(filename, "utf-8");
  if(!f.contents) {
    f.contents = content;
  } else {
    if (f.contents !== content) {
      f.contents = content;
      f.version = parseInt(f.version) + 1
    }
  }
  
  return f.contents;
}
```

**Comment by tsne** [comment]
Thanks for pointing out. I already removed the file store in the last version. Could you please update the package to version 1.1.5?

**Comment by limbowang** [comment]
It works! Thanks~
