### ISSUE TITLE
Support to transform previous plugin result

### ISSUE THREAD

**Issue by chinesedfan** [tsne/rollup-plugin-tsc#4]
Suppose `plugin-xx` will transform `file.xx` to Typescript content. And we put this plugin after `plugin-xx`, i.e. `[plugin-xx(), tscPlugin]`. Because of `service.filter(id)` and `file.xx` is not contained by the file store, this plugin will skip to transform previous plugin result.

Maybe we need add an option, like a callback `shouldTransformDirectly` or something else, to allow files beyond the file store to be transformed by `ts.transpileModule`. Waiting for better suggestions.

**Comment by chinesedfan** [comment]
I just noticed that `isolatedModules` will be `true` unconditionally. So if previous result includes `import 'other-files'`, there may be problems.

**Comment by chinesedfan** [comment]
@tsne After some investigations, I find [rollup-plugin-typescript](https://github.com/rollup/rollup-plugin-typescript) shares the same idea to use ts.transpileModule and also faces situations that can't emit errors across files, while [rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2) leverages ts.languageService like this plugin.

> As I played with this yesterday, I was not able to make getEmitOutput aware of the .xx files.

For this problem, I got a tricky way. If the previous plugin resolves `.xx` ids to an existed file which has been added to the language service, like an empty ts file `placeholder.ts`, this plugin and rollup-plugin-typescript2 both works. I don't know details of the language service and what disadvantages of this method are, but it seems `placeholder.ts` will not be modified and the result is right.

**Comment by ezolenko** [comment]
Having actual files shouldn't be necessary, as long as your implementation of `typescript.LanguageServiceHost` return them properly in `getScriptFileNames` and `getScriptSnapshot`. The linked issue in rpt2 seem to be in the plugin actually seeing the files from rollup at all.

**Comment by tsne** [comment]
Hi,

after some more investigation into this issue, I finally found an option called `allowNonTsExtensions`. This should allow the internal compiler to also see files without `.ts`/`.tsx`/`.js`/`.jsx` extension.

@chinesedfan Could you please upgrade the plugin to version `1.1.12` and try again? If it does not work, can you please provide a sample repository where the issue occurs?

@ezolenko Thanks for you feedback. `getScriptFileNames` and `getScriptSnapshot` should have returned the files properly. As far as I could find, there was still an internal filter which only made file with the default Typescript extension visible.

**Comment by chinesedfan** [comment]
@ezolenko @tsne Sorry for the late repository, [chinesedfan/rollup-pipe-ts-plugin-issue](https://github.com/chinesedfan/rollup-pipe-ts-plugin-issue). Currently, it uses my tricky holder-strategy with the latest rollup-plugin-tsc/rpt2 and works normally.

If trying to avoid the holder file, which I think is deleting [this line](https://github.com/chinesedfan/rollup-pipe-ts-plugin-issue/blob/master/rollup.config.js#L11), then something is wrong.
```
// for rollup-plugin-tsc
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)

// for rpt2
[!] (rpt2 plugin) Error: Could not find file: '/Users/zhong/Desktop/test/tstest/entry.xx'.
```

**Comment by tsne** [comment]
@chinesedfan Thank you for the sample repository. I pushed version `1.1.13` which should work now. It would be great, if you could test the changes.
